config/routes.rb
Rails.application.routes.draw do
  root 'home#top'
  
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }

  devise_scope :user do
    get 'guest_login', to: 'users/sessions#guest_login'
  end

  get 'home/index', to: 'home#index'

  resources :users

  resources :onsens do
    collection do
      get 'region/:region', to: 'onsens#region', as: 'region'
      get 'region/:region/prefecture/:prefecture', to: 'onsens#prefecture', as: 'prefecture'
      get 'bookmarked', to: 'onsens#bookmarked', as: 'bookmarked'
      get 'search'
      get 'detail_search'
      get 'search_with_details'
    end
  
    member do
      post :bookmark
      delete :destroy 
    end
  end
end

app/models/onsen.rb
class Onsen < ApplicationRecord
  belongs_to :user
  belongs_to :saved_by_user, class_name: 'User', optional: true
  has_many_attached :images
  has_many :image_descriptions, dependent: :destroy
  has_many :saved_onsens, dependent: :destroy
  has_many :users, through: :saved_onsens
  has_and_belongs_to_many :water_qualities

  validates :name, presence: true

  def self.prefectures
    [
      ['北海道', '北海道'],
      ['青森県', '青森県'],
      ['岩手県', '岩手県'],
      ['宮城県', '宮城県'],
      ['秋田県', '秋田県'],
      ['山形県', '山形県'],
      ['福島県', '福島県'],
      ['茨城県', '茨城県'],
      ['栃木県', '栃木県'],
      ['群馬県', '群馬県'],
      ['埼玉県', '埼玉県'],
      ['千葉県', '千葉県'],
      ['東京都', '東京都'],
      ['神奈川県', '神奈川県'],
      ['新潟県', '新潟県'],
      ['富山県', '富山県'],
      ['石川県', '石川県'],
      ['福井県', '福井県'],
      ['山梨県', '山梨県'],
      ['長野県', '長野県'],
      ['岐阜県', '岐阜県'],
      ['静岡県', '静岡県'],
      ['愛知県', '愛知県'],
      ['三重県', '三重県'],
      ['滋賀県', '滋賀県'],
      ['京都府', '京都府'],
      ['大阪府', '大阪府'],
      ['兵庫県', '兵庫県'],
      ['奈良県', '奈良県'],
      ['和歌山県', '和歌山県'],
      ['鳥取県', '鳥取県'],
      ['島根県', '島根県'],
      ['岡山県', '岡山県'],
      ['広島県', '広島県'],
      ['山口県', '山口県'],
      ['徳島県', '徳島県'],
      ['香川県', '香川県'],
      ['愛媛県', '愛媛県'],
      ['高知県', '高知県'],
      ['福岡県', '福岡県'],
      ['佐賀県', '佐賀県'],
      ['長崎県', '長崎県'],
      ['熊本県', '熊本県'],
      ['大分県', '大分県'],
      ['宮崎県', '宮崎県'],
      ['鹿児島県', '鹿児島県'],
      ['沖縄県', '沖縄県'],
    ]
  end

  def region
    case location
    when '北海道'
      '北海道'
    when '青森県', '岩手県', '宮城県', '秋田県', '山形県', '福島県'
      '東北'
    when '茨城県', '栃木県', '群馬県', '埼玉県', '千葉県', '東京都', '神奈川県'
      '関東'
    when '新潟県', '富山県', '石川県', '福井県', '山梨県', '長野県', '岐阜県', '静岡県', '愛知県'
      '中部'
    when '三重県', '滋賀県', '京都府', '大阪府', '兵庫県', '奈良県', '和歌山県'
      '近畿'
    when '鳥取県', '島根県', '岡山県', '広島県', '山口県'
      '中国'
    when '徳島県', '香川県', '愛媛県', '高知県'
      '四国'
    when '福岡県', '佐賀県', '長崎県', '熊本県', '大分県', '宮崎県', '鹿児島県', '沖縄県'
      '九州・沖縄'
    else
      '不明'
    end
  end

  def self.region_locations(region)
    case region
    when '北海道'
      ['北海道']
    when '東北'
      ['青森県', '岩手県', '宮城県', '秋田県', '山形県', '福島県']
    when '関東'
      ['茨城県', '栃木県', '群馬県', '埼玉県', '千葉県', '東京都', '神奈川県']
    when '中部'
      ['新潟県', '富山県', '石川県', '福井県', '山梨県', '長野県', '岐阜県', '静岡県', '愛知県']
    when '近畿'
      ['三重県', '滋賀県', '京都府', '大阪府', '兵庫県', '奈良県', '和歌山県']
    when '中国'
      ['鳥取県', '島根県', '岡山県', '広島県', '山口県']
    when '四国'
      ['徳島県', '香川県', '愛媛県', '高知県']
    when '九州・沖縄'
      ['福岡県', '佐賀県', '長崎県', '熊本県', '大分県', '宮崎県', '鹿児島県', '沖縄県']
    else
      []
    end
  end

  def self.region_order
    {
      '北海道' => 0,
      '東北' => 1,
      '関東' => 2,
      '中部' => 3,
      '近畿' => 4,
      '中国' => 5,
      '四国' => 6,
      '九州・沖縄' => 7,
    }
  end

  def self.prefecture_order
    {
      '北海道' => 0,
      '青森県' => 1,
      '岩手県' => 2,
      '宮城県' => 3,
      '秋田県' => 4,
      '山形県' => 5,
      '福島県' => 6,
      '茨城県' => 7,
      '栃木県' => 8,
      '群馬県' => 9,
      '埼玉県' => 10,
      '千葉県' => 11,
      '東京都' => 12,
      '神奈川県' => 13,
      '新潟県' => 14,
      '富山県' => 15,
      '石川県' => 16,
      '福井県' => 17,
      '山梨県' => 18,
      '長野県' => 19,
      '岐阜県' => 20,
      '静岡県' => 21,
      '愛知県' => 22,
      '三重県' => 23,
      '滋賀県' => 24,
      '京都府' => 25,
      '大阪府' => 26,
      '兵庫県' => 27,
      '奈良県' => 28,
      '和歌山県' => 29,
      '鳥取県' => 30,
      '島根県' => 31,
      '岡山県' => 32,
      '広島県' => 33,
      '山口県' => 34,
      '徳島県' => 35,
      '香川県' => 36,
      '愛媛県' => 37,
      '高知県' => 38,
      '福岡県' => 39,
      '佐賀県' => 40,
      '長崎県' => 41,
      '熊本県' => 42,
      '大分県' => 43,
      '宮崎県' => 44,
      '鹿児島県' => 45,
      '沖縄県' => 46,
    }
  end
end

app/controllers/onsens_controller.rb
class OnsensController < ApplicationController
  before_action :authenticate_user!
  before_action :check_guest_user, only: [:new, :create, :edit, :update, :destroy]
  before_action :transfer_guest_bookmarks, only: [:bookmarked, :bookmark], if: :user_signed_in?

  def index
    if params[:sort] == "bookmarks"
      location_order_sql = Onsen.prefecture_order.map { |pref, order| "WHEN '#{pref}' THEN #{order}" }.join(' ')

      @onsens = Onsen.
        left_joins(:saved_onsens).
        group('onsens.id').
        select('onsens.*, COUNT(saved_onsens.id) AS bookmarks_count').
        order(Arel.sql("COUNT(saved_onsens.id) DESC, CASE onsens.location #{location_order_sql} ELSE 999 END, onsens.id ASC")).
        limit(10)
    else
      @onsens = Onsen.all.sort_by do |onsen|
        [
          Onsen.region_order[onsen.region],
          Onsen.prefecture_order[onsen.location],
        ]
      end
    end

    @current_region = 'トップ'
    @page_title = "全国の温泉"
  end

  def region
    @region = params[:region]
    @current_region = @region
    @prefectures = Onsen.region_locations(@region)

    if params[:sort] == "bookmarks"
      location_order_sql = Onsen.prefecture_order.map { |pref, order| "WHEN '#{pref}' THEN #{order}" }.join(' ')

      @onsens = Onsen.where(location: @prefectures).
        left_joins(:saved_onsens).
        group('onsens.id').
        select('onsens.*, COUNT(saved_onsens.id) AS bookmarks_count').
        order(Arel.sql("COUNT(saved_onsens.id) DESC, CASE onsens.location #{location_order_sql} ELSE 999 END, onsens.id ASC"))
    else
      @onsens = Onsen.where(location: @prefectures).sort_by do |onsen|
        Onsen.prefecture_order[onsen.location]
      end
    end
    @page_title = "#{@region}の温泉"
  end

  def prefecture
    @prefecture = params[:prefecture]
    @onsens = Onsen.where(location: @prefecture)

    if params[:sort] == "bookmarks"
      @onsens = Onsen.where(location: @prefecture).
        left_joins(:saved_onsens).
        group('onsens.id').
        select('onsens.*, COUNT(saved_onsens.id) AS bookmarks_count').
        order(Arel.sql("COUNT(saved_onsens.id) DESC, onsens.id ASC"))
    else
      @onsens = Onsen.where(location: @prefecture).order(:id)
    end
    @page_title = "#{@prefecture}の温泉"
  end

  def show
    @onsen = Onsen.includes(:water_qualities, :image_descriptions).find(params[:id])
    @user = current_user
    @saved_onsens = @user.saved_onsens.includes(:onsen) if @user
    @posted_onsens = @user.onsens if @user
    @page_title = @onsen.name
  end

  def new
    @onsen = Onsen.new
    @page_title = "編集ページ"
  end

  def edit
    @onsen = Onsen.find(params[:id])
    @page_title = "温泉情報設定"
    @new_images = params[:onsen] ? params[:onsen][:images] : []
  end

  def create
    unless current_user
      flash[:alert] = I18n.t('alerts.login_required')
      redirect_to new_user_session_path && return
    end

    @onsen = current_user.onsens.build(onsen_params)

    existing_onsen = Onsen.find_by(name: onsen_params[:name], location: onsen_params[:location])

    if existing_onsen
      @error_message = I18n.t('alerts.onsen_already_exists')
      render :new
      return
    end

    if @onsen.save
      if params[:onsen][:new_descriptions].present?
        params[:onsen][:new_descriptions].each_with_index do |description, index|
          if @onsen.images.attached? && index < @onsen.images.count
            @onsen.image_descriptions.create(description: description)
          end
        end
      end

      redirect_to @onsen, notice: I18n.t('notices.onsen_created')
    else
      flash.now[:alert] = I18n.t('alerts.post_failed')
      render :new
    end
  end

  def update
    unless current_user
      flash[:alert] = I18n.t('alerts.login_required')
      redirect_to new_user_session_path && return
    end

    @onsen = current_user.onsens.find(params[:id])

    existing_onsen = Onsen.where.not(id: @onsen.id).find_by(name: onsen_params[:name], location: onsen_params[:location])
    if existing_onsen
      @error_message = I18n.t('alerts.onsen_already_exists')
      render :edit
      return
    end

    new_images = params[:onsen][:images].compact_blank if params[:onsen][:images].present?
    new_descriptions = params[:onsen][:new_descriptions].compact_blank if params[:onsen][:new_descriptions].present?

    if @onsen.update(onsen_params.except(:images, :image_descriptions))
      if new_images.present?
        @onsen.images.destroy_all
        @onsen.image_descriptions.destroy_all
        @onsen.images.attach(new_images)

        if new_descriptions.present?

          new_descriptions.each_with_index do |description, index|
            if @onsen.images.attached? && index < @onsen.images.count
              @onsen.image_descriptions.create(description: description)
            end
          end
        end
      end

      redirect_to @onsen, notice: I18n.t('notices.onsen_updated')
    else
      flash.now[:alert] = I18n.t('alerts.update_failed')
      render :edit
    end
  end

  def bookmark
    @onsen = Onsen.find(params[:onsen_id])
    saved_onsen = SavedOnsen.find_or_initialize_by(user: current_user, onsen: @onsen)

    if saved_onsen.new_record?
      saved_onsen.save
      saved = true
    else
      saved_onsen.destroy
      saved = false
    end

    bookmarked_count = @onsen.saved_onsens.count

    respond_to do |format|
      format.json { render json: { saved: saved, bookmarked_count: bookmarked_count } }
      format.html { redirect_to onsens_path }
    end
  end

  def bookmarked
    @page_title = "保存済みの温泉"

    if params[:sort] == "bookmarks"
      @onsens = current_user.saved_onsens.
        includes(:onsen).
        map(&:onsen).
        sort_by { |onsen| -onsen.saved_onsens.count }
    else
      @onsens = current_user.saved_onsens.
        includes(:onsen).
        map(&:onsen).
        sort_by do |onsen|
        [Onsen.region_order[onsen.region], Onsen.prefecture_order[onsen.location]]
      end
    end
  end

  def destroy
    @onsen = Onsen.find(params[:id])

    if @onsen.destroy
      redirect_to onsens_path, notice: I18n.t('notices.onsen_deleted')
    else
      redirect_to onsens_path, alert: I18n.t('alerts.delete_failed')
    end
  end

  def search
    @keyword = params[:keyword]

    if @keyword.present?
      @onsens = Onsen.where("onsens.name LIKE ?", "%#{@keyword}%").distinct
    else
      @onsens = []
    end

    @onsens = @onsens.sort_by do |onsen|
      [
        Onsen.region_order[onsen.region],
        Onsen.prefecture_order[onsen.location],
      ]
    end.uniq

    @page_title = "検索結果"
  end

  def detail_search
    @locations = Onsen.prefectures
    @water_qualities = WaterQuality.all
    @page_title = "詳細検索"
  end

  def search_with_details
    @keyword = params[:keyword]
    @location = params[:location]
    @water_quality_ids = params[:water_quality_ids].compact_blank

    @onsens = Onsen.all

    if @keyword.present?
      @onsens = @onsens.where("onsens.name LIKE ?", "%#{@keyword}%").distinct
    end

    if @location.present?
      @onsens = @onsens.where(location: @location)
    end

    if @water_quality_ids.present?
      @onsens = @onsens.joins(:water_qualities).where(water_qualities: { id: @water_quality_ids })
    end

    @onsens = @onsens.to_a

    @onsens = @onsens.sort_by do |onsen|
      [
        Onsen.region_order[onsen.region],
        Onsen.prefecture_order[onsen.location],
      ]
    end.uniq

    render 'search'
  end

  private

  def check_guest_user
    if current_user.guest?
      flash[:alert] = I18n.t('alerts.guest_user')

      if request.get?
        redirect_back(fallback_location: home_index_path)
      else
        redirect_to onsens_path
      end
    end
  end

  def transfer_guest_bookmarks
    return if session[:bookmarked_onsens].blank?

    onsen_ids = session[:bookmarked_onsens].compact.uniq

    existing_onsen_ids = SavedOnsen.where(user: current_user, onsen_id: onsen_ids).pluck(:onsen_id)
    new_onsen_ids = onsen_ids - existing_onsen_ids

    new_onsen_ids.each do |onsen_id|
      SavedOnsen.create(user: current_user, onsen_id: onsen_id)
    end

    session.delete(:bookmarked_onsens)
  end

  def onsen_params
    params.require(:onsen).permit(
      :name,
      :location,
      water_quality_ids: [],
      images: [],
      image_descriptions: []
    )
  end
end

app/helpers/onsens_helper.rb
module OnsensHelper
end

app/views/onsens/_region-nav.html.erb
<nav class="region-nav">
  <ul class="menu-list">
    <li class="menu-item <%= 'current' if @current_region == 'トップ' %>">
      <%= link_to 'トップ', onsens_path, class: 'region-link' %>
    </li>
    <li class="menu-item <%= 'current' if @current_region == '北海道' %>">
      <%= link_to '北海道', region_onsens_path(region: '北海道'), class: 'region-link' %>
      <ul class="drop-menu-list">
        <% Onsen.region_locations('北海道').each do |prefecture| %>
          <li class="drop-menu-item"><%= link_to prefecture, prefecture_onsens_path(region: '北海道', prefecture: prefecture) %></li>
        <% end %>
      </ul>
    </li>
    <li class="menu-item <%= 'current' if @current_region == '東北' %>">
      <%= link_to '東北', region_onsens_path(region: '東北'), class: 'region-link' %>
      <ul class="drop-menu-list">
        <% Onsen.region_locations('東北').each do |prefecture| %>
          <li class="drop-menu-item"><%= link_to prefecture, prefecture_onsens_path(region: '東北', prefecture: prefecture) %></li>
        <% end %>
      </ul>
    </li>
    <li class="menu-item <%= 'current' if @current_region == '関東' %>">
      <%= link_to '関東', region_onsens_path(region: '関東'), class: 'region-link' %>
      <ul class="drop-menu-list">
        <% Onsen.region_locations('関東').each do |prefecture| %>
          <li class="drop-menu-item"><%= link_to prefecture, prefecture_onsens_path(region: '関東', prefecture: prefecture) %></li>
        <% end %>
      </ul>
    </li>
    <li class="menu-item <%= 'current' if @current_region == '中部' %>">
      <%= link_to '中部', region_onsens_path(region: '中部'), class: 'region-link' %>
      <ul class="drop-menu-list">
        <% Onsen.region_locations('中部').each do |prefecture| %>
          <li class="drop-menu-item"><%= link_to prefecture, prefecture_onsens_path(region: '中部', prefecture: prefecture) %></li>
        <% end %>
      </ul>
    </li>
    <li class="menu-item <%= 'current' if @current_region == '近畿' %>">
      <%= link_to '近畿', region_onsens_path(region: '近畿'), class: 'region-link' %>
      <ul class="drop-menu-list">
        <% Onsen.region_locations('近畿').each do |prefecture| %>
          <li class="drop-menu-item"><%= link_to prefecture, prefecture_onsens_path(region: '近畿', prefecture: prefecture) %></li>
        <% end %>
      </ul>
    </li>
    <li class="menu-item <%= 'current' if @current_region == '中国' %>">
      <%= link_to '中国', region_onsens_path(region: '中国'), class: 'region-link' %>
      <ul class="drop-menu-list">
        <% Onsen.region_locations('中国').each do |prefecture| %>
          <li class="drop-menu-item"><%= link_to prefecture, prefecture_onsens_path(region: '中国', prefecture: prefecture) %></li>
        <% end %>
      </ul>
    </li>
    <li class="menu-item <%= 'current' if @current_region == '四国' %>">
      <%= link_to '四国', region_onsens_path(region: '四国'), class: 'region-link' %>
      <ul class="drop-menu-list">
        <% Onsen.region_locations('四国').each do |prefecture| %>
          <li class="drop-menu-item"><%= link_to prefecture, prefecture_onsens_path(region: '四国', prefecture: prefecture) %></li>
        <% end %>
      </ul>
    </li>
    <li class="menu-item <%= 'current' if @current_region == '九州・沖縄' %>">
      <%= link_to '九州・沖縄', region_onsens_path(region: '九州・沖縄'), class: 'region-link' %>
      <ul class="drop-menu-list">
        <% Onsen.region_locations('九州・沖縄').each do |prefecture| %>
          <li class="drop-menu-item"><%= link_to prefecture, prefecture_onsens_path(region: '九州・沖縄', prefecture: prefecture) %></li>
        <% end %>
      </ul>
    </li>
  </ul>
</nav>

app/views/onsens/bookmarked.html.erb
<%= render 'onsens/region-nav' %>

<div class="onsen-list">
  <h2 class="heading-9">ブックマークした温泉</h2>
  <div class="sort-dropdown">
    <select id="sort-select">
      <option value="<%= bookmarked_onsens_path %>" <%= params[:sort].nil? ? 'selected' : '' %>>都道府県順</option>
      <option value="<%= bookmarked_onsens_path(sort: 'bookmarks') %>" <%= params[:sort] == 'bookmarks' ? 'selected' : '' %>>人気順</option>
    </select>
  </div>
  <div class="d-flex flex-wrap">
    <% @onsens.each do |onsen| %>
      <div class="card onsen-card shadow-lg position-relative">
        <div class="onsen-card-body">
          <% if onsen.images.attached? %>
            <%= link_to image_tag(onsen.images.first, class: 'card-img-top'), onsen_path(onsen) %>
          <% else %>
            <img src="<%= asset_path('default_onsen_image.png') %>" alt="デフォルトの温泉画像" class="image-placeholder" />
          <% end %>
          <h5 class="cardtitle">
            <%= link_to onsen.name, onsen_path(onsen), class: 'card-title' %>
          </h5>
          <p class="prefecture-name"><%= onsen.location %></p>
          <p class="last-updated">最終更新日: <%= onsen.updated_at.strftime('%Y年%m月%d日') %></p>
          <p class="saved-count">保存された数: <span id="count-<%= onsen.id %>"><%= onsen.saved_onsens.count %></span> 件</p>
        </div>
        
        <div class="table-save-button">
          <button class="save-button <%= current_user.saved_onsens.exists?(onsen_id: onsen.id) ? 'saved' : '' %>" 
                  title="ブックマーク" 
                  data-onsen-id="<%= onsen.id %>"
                  id="bookmark-button-<%= onsen.id %>">
            <i class="fas fa-bookmark<%= current_user.saved_onsens.exists?(onsen_id: onsen.id) ? '' : '-o' %>"></i>
          </button>

          <%= form_with(url: bookmark_onsen_path(onsen), method: :post, local: true, id: "bookmark-form-#{onsen.id}") do %>
            <%= hidden_field_tag :onsen_id, onsen.id %>
          <% end %>       
        </div>


      </div>
    <% end %>
  </div>
</div>

app/views/onsens/index.html.erb
<%= render 'onsens/region-nav' %>

<div class="onsen-list">
  <h2 class="heading-9">全国の温泉</h2>
  <div class="sort-dropdown">
    <select id="sort-select">
      <option value="<%= onsens_path %>" <%= params[:sort].nil? ? 'selected' : '' %>>都道府県順</option>
      <option value="<%= onsens_path(sort: 'bookmarks') %>" <%= params[:sort] == 'bookmarks' ? 'selected' : '' %>>人気順</option>
    </select>
  </div>
  <div class="d-flex flex-wrap">
    <% @onsens.each do |onsen| %>
      <div class="card onsen-card shadow-lg position-relative">
        <div class="onsen-card-body">
          <% if onsen.images.attached? %>
            <%= link_to image_tag(onsen.images.first, class: 'card-img-top'), onsen_path(onsen) %>
          <% else %>
            <img src="<%= asset_path('default_onsen_image.png') %>" alt="デフォルトの温泉画像" class="image-placeholder" />
          <% end %>
          <h5 class="cardtitle">
            <%= link_to onsen.name, onsen_path(onsen), class: 'card-title' %>
          </h5>
          <p class="prefecture-name"><%= onsen.location %></p>
          <p class="last-updated">最終更新日: <%= onsen.updated_at.strftime('%Y年%m月%d日') %></p>
          <p class="saved-count">保存された数: <span id="count-<%= onsen.id %>"><%= onsen.saved_onsens.count %></span> 件</p>
        </div>
        
        <div class="table-save-button">
          <button class="save-button <%= current_user.saved_onsens.exists?(onsen_id: onsen.id) ? 'saved' : '' %>" 
                  title="ブックマーク" 
                  data-onsen-id="<%= onsen.id %>"
                  id="bookmark-button-<%= onsen.id %>">
            <i class="fas fa-bookmark<%= current_user.saved_onsens.exists?(onsen_id: onsen.id) ? '' : '-o' %>"></i>
          </button>

          <%= form_with(url: bookmark_onsen_path(onsen), method: :post, local: true, id: "bookmark-form-#{onsen.id}") do %>
            <%= hidden_field_tag :onsen_id, onsen.id %>
          <% end %>       
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/onsens/prefecture.html.erb
<%= render 'onsens/region-nav' %>

<div class="prefecture-onsen-list">
  <h2 class="heading-9"><%= @prefecture %>の温泉</h2>
  <div class="sort-dropdown">
    <select id="sort-select">
      <option value="<%= prefecture_onsens_path(prefecture: @prefecture) %>" <%= params[:sort].nil? ? 'selected' : '' %>>都道府県順</option>
      <option value="<%= prefecture_onsens_path(prefecture: @prefecture, sort: 'bookmarks') %>" <%= params[:sort] == 'bookmarks' ? 'selected' : '' %>>人気順</option>
    </select>
  </div>
  <div class="d-flex flex-wrap">
      <% @onsens.each do |onsen| %>
      <div class="card onsen-card shadow-lg">
        <div class="onsen-card-body">
          <% if onsen.images.attached? %>
            <%= link_to image_tag(onsen.images.first, class: 'card-img-top'), onsen_path(onsen) %>
          <% else %>
            <img src="<%= asset_path('default_onsen_image.png') %>" alt="デフォルトの温泉画像" class="image-placeholder" />
          <% end %>
          <h5 class="cardtitle">
            <%= link_to onsen.name, onsen_path(onsen), class: 'card-title' %>
          </h5>
          <p class="prefecture-name"><%= onsen.location %></p>
          <p class="last-updated">最終更新日: <%= onsen.updated_at.strftime('%Y年%m月%d日') %></p>
          <p class="saved-count">保存された数: <span id="count-<%= onsen.id %>"><%= onsen.saved_onsens.count %></span> 件</p>
          <div class="table-save-button">
            <button class="save-button <%= current_user.saved_onsens.exists?(onsen_id: onsen.id) ? 'saved' : '' %>" 
                    title="ブックマーク" 
                    data-onsen-id="<%= onsen.id %>"
                    id="bookmark-button-<%= onsen.id %>">
              <i class="fas fa-bookmark<%= current_user.saved_onsens.exists?(onsen_id: onsen.id) ? '' : '-o' %>"></i>
            </button>

            <%= form_with(url: bookmark_onsen_path(onsen), method: :post, local: true, id: "bookmark-form-#{onsen.id}") do %>
              <%= hidden_field_tag :onsen_id, onsen.id %>
            <% end %>       
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/onsens/region.html.erb
<%= render 'onsens/region-nav' %>

<div class="region-onsen-list">
  <h2 class="heading-9"><%= @current_region %>の温泉</h2>
  <div class="sort-dropdown">
    <select id="sort-select">
      <option value="<%= region_onsens_path(region: @region) %>" <%= params[:sort].nil? ? 'selected' : '' %>>都道府県順</option>
      <option value="<%= region_onsens_path(region: @region, sort: 'bookmarks') %>" <%= params[:sort] == 'bookmarks' ? 'selected' : '' %>>人気順</option>
    </select>
  </div>
  <div class="d-flex flex-wrap">
    <% @onsens.each do |onsen| %>
      <div class="card onsen-card shadow-lg">
        <div class="onsen-card-body">
          <% if onsen.images.attached? %>
            <%= link_to image_tag(onsen.images.first, class: 'card-img-top'), onsen_path(onsen) %>
          <% else %>
            <img src="<%= asset_path('default_onsen_image.png') %>" alt="デフォルトの温泉画像" class="image-placeholder" />
          <% end %>
          <h5 class="cardtitle">
            <%= link_to onsen.name, onsen_path(onsen), class: 'card-title' %>
          </h5>
          <p class="prefecture-name"><%= onsen.location %></p>
          <p class="last-updated">最終更新日: <%= onsen.updated_at.strftime('%Y年%m月%d日') %></p>
          <p class="saved-count">保存された数: <span id="count-<%= onsen.id %>"><%= onsen.saved_onsens.count %></span> 件</p>
          <div class="table-save-button">
            <button class="save-button <%= current_user.saved_onsens.exists?(onsen_id: onsen.id) ? 'saved' : '' %>" 
                    title="ブックマーク" 
                    data-onsen-id="<%= onsen.id %>"
                    id="bookmark-button-<%= onsen.id %>">
              <i class="fas fa-bookmark<%= current_user.saved_onsens.exists?(onsen_id: onsen.id) ? '' : '-o' %>"></i>
            </button>

            <%= form_with(url: bookmark_onsen_path(onsen), method: :post, local: true, id: "bookmark-form-#{onsen.id}") do %>
              <%= hidden_field_tag :onsen_id, onsen.id %>
            <% end %>       
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>