config/routes.rb
Rails.application.routes.draw do
  root 'home#top'
  
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }

  devise_scope :user do
    get 'guest_login', to: 'users/sessions#guest_login'
  end

  get 'home/index', to: 'home#index'

  resources :users

  resources :onsens do
    collection do
      get 'region/:region', to: 'onsens#region', as: 'region'
      get 'region/:region/prefecture/:prefecture', to: 'onsens#prefecture', as: 'prefecture'
      get 'bookmarked', to: 'onsens#bookmarked', as: 'bookmarked'
      get 'search'
      get 'detail_search'
      get 'search_with_details'
    end
  
    member do
      post :bookmark
      delete :destroy 
    end
  end
end

app/views/layouts/_flash_messages.html.erb
<% if flash[:alert] %>
  <div class="alert alert-danger">
    <%= flash[:alert] %>
  </div>
<% end %>
<% if flash[:notice] %>
  <div class="alert alert-success">
    <%= flash[:notice] %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<div class="footer-content">
  <p class="footer-copyright">&copy; 2024 ri914. All Rights Reserved.</p>
  <p class="footer-description">温泉オンラインは現地の人々とリアルタイムでつながる温泉情報共有サイトです</p>
  <p class="footer-skills">使用技術: <span>Ruby on Rails, HTML, CSS, JavaScript, Bootstrap</span></p>
  <p class="footer-contact">お問い合わせ: <a href="mailto:issue914@gmail.com">issue914@gmail.com</a></p>    
  <div class="footer-social-media">
    <a href="https://github.com/ri914" target="_blank" class="social-icon"><i class="fab fa-github"></i></a>
  </div>
</div>

app/views/layouts/_head.html.erb
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<title><%= full_title(page_title: @page_title) %></title>

<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Reggae+One&family=Yuji+Mai&family=Yuji+Syuku&display=swap" rel="stylesheet">

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js" integrity="sha384-fbbOQedDUMZZ5KreZpsbe1LCZPVmfTnH7ois6mU1QK+m14rQ1l2bGBq41eYeM/fS" crossorigin="anonymous"></script>

<%= javascript_include_tag 'application', 'data-turbo-track': 'reload' %>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav mx-auto">
        <% if user_signed_in? %>
          <li class="nav-item dropdown me-2">
            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <% if current_user.email == 'guest@example.com' %>
                <%= image_tag 'default_avatar.png', class: "nav-avatar" %> ゲスト
              <% else %>
                <% if current_user.avatar.attached? %>
                  <%= image_tag current_user.avatar, class: "nav-avatar" %>
                <% else %>
                  <%= image_tag 'default_avatar.png', class: "nav-avatar" %>
                <% end %>
                <%= current_user.name %>
              <% end %>
            </a>
            <ul class="dropdown-menu" aria-labelledby="userDropdown">
              <li><a class="dropdown-item" href="<%= user_path(current_user) %>"><i class="fas fa-user-circle"></i> マイページ</a></li>
              <li>
                <a class="dropdown-item user-dropdown-link" href="<%= edit_user_registration_path %>" data-guest="<%= current_user.guest? %>">
                  <i class="fas fa-cog"></i> 設定
                </a>
              </li>
              <li class="nav-item">
                <%= form_with url: destroy_user_session_path, method: :delete, local: true do |form| %>
                  <button type="submit" class="dropdown-item d-flex align-items-center" onclick="return confirm('ログアウトしますか？');">
                    <i class="fas fa-sign-out-alt me-2"></i> ログアウト
                  </button>
                <% end %>
              </li>
              <li class="nav-item">
                <%= form_with url: user_path(current_user), method: :delete, local: true do |form| %>
                  <button type="submit" class="dropdown-item d-flex align-items-center user-dropdown-link" data-guest="<%= current_user.guest? %>" onclick="return confirm('本当に退会しますか？');">
                    <i class="fas fa-user-slash me-2"></i> 退会
                  </button>
                <% end %>
              </li>
            </ul>
          </li>

          <li class="nav-item">
            <a class="nav-link active" href="<%= home_index_path %>">
              <i class="fas fa-home"></i> ホーム
            </a>
          </li>

          <li class="nav-item">
            <a class="nav-link post-link" href="<%= new_onsen_path %>" data-guest="<%= current_user.guest? %>">
              <i class="fas fa-plus-circle"></i> 投稿
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= onsens_path %>">
              <i class="fas fa-hot-tub"></i>
              <span class="d-none d-lg-inline"> 温泉地一覧</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= bookmarked_onsens_path %>">
              <i class="fas fa-bookmark"></i> 保存済み
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= detail_search_onsens_path %>">
              <i class="fas fa-search-plus"></i> 詳細検索
            </a>
          </li>
          <li class="nav-item">
            <div class="d-flex align-items-center">
              <%= form_with url: search_onsens_path, method: :get, local: true, class: "d-flex me-2" do |form| %>
                <div class="input-group">
                  <%= form.text_field :keyword, size: 25, placeholder: 'キーワードを入力...', class: "form-control search-input" %>
                  <button class="btn btn-primary" type="submit">
                    <i class="fas fa-search"></i>
                  </button>
                </div>
              <% end %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <a class="nav-link active" href="<%= root_path %>">
              <i class="fas fa-home"></i> ホーム
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= new_user_registration_path %>">
              <i class="fas fa-user-plus"></i> 新規登録
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= new_user_session_path %>">
              <i class="fas fa-sign-in-alt"></i> ログイン
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= guest_login_path %>">
              <i class="fas fa-user-friends"></i> ゲストログイン
            </a>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html lang="ja">
  <body>

    <%= render 'layouts/head' %>

    <%= render 'layouts/nav' %>
    
    <%= render 'layouts/flash_messages' %>
    
    <%= yield %>
    
    <footer class="footer">
      <%= render 'layouts/footer' %> 
    </footer>

  </body>
</html>